contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/strandedathome/rolls-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/strandedathome/rolls-blockchain/discussions/new?category=ideas
  - about: Get support on the PecanRolls Discord.
    name: Join Rolls Discord
    url: 'https://discord.gg/xA9FHJpfEB'
